/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _CLAVESRPC_H_RPCGEN
#define _CLAVESRPC_H_RPCGEN

#include <rpc/rpc.h>

#include <pthread.h>

#ifdef __cplusplus
extern "C" {
#endif


struct p_paquete {
	int x;
	int y;
	int z;
};
typedef struct p_paquete p_paquete;

struct params {
	char *key;
	char *value1;
	int N_value2;
	struct {
		u_int V_value2_len;
		float *V_value2_val;
	} V_value2;
	struct p_paquete value3;
};
typedef struct params params;

struct get_value_res {
	int result;
	char *value1;
	int N_value2;
	struct {
		u_int V_value2_len;
		float *V_value2_val;
	} V_value2;
	struct p_paquete value3;
};
typedef struct get_value_res get_value_res;

#define CLAVES_RPC 99
#define CLAVES_VER 1

#if defined(__STDC__) || defined(__cplusplus)
#define DESTROY 1
extern  enum clnt_stat destroy_1(int *, CLIENT *);
extern  bool_t destroy_1_svc(int *, struct svc_req *);
#define SET_VALUE 2
extern  enum clnt_stat set_value_1(struct params , int *, CLIENT *);
extern  bool_t set_value_1_svc(struct params , int *, struct svc_req *);
#define GET_VALUE 3
extern  enum clnt_stat get_value_1(char *, struct get_value_res *, CLIENT *);
extern  bool_t get_value_1_svc(char *, struct get_value_res *, struct svc_req *);
#define MODIFY_VALUE 4
extern  enum clnt_stat modify_value_1(struct params , int *, CLIENT *);
extern  bool_t modify_value_1_svc(struct params , int *, struct svc_req *);
#define DELETE_KEY 5
extern  enum clnt_stat delete_key_1(char *, int *, CLIENT *);
extern  bool_t delete_key_1_svc(char *, int *, struct svc_req *);
#define EXIST 6
extern  enum clnt_stat exist_1(char *, int *, CLIENT *);
extern  bool_t exist_1_svc(char *, int *, struct svc_req *);
extern int claves_rpc_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define DESTROY 1
extern  enum clnt_stat destroy_1();
extern  bool_t destroy_1_svc();
#define SET_VALUE 2
extern  enum clnt_stat set_value_1();
extern  bool_t set_value_1_svc();
#define GET_VALUE 3
extern  enum clnt_stat get_value_1();
extern  bool_t get_value_1_svc();
#define MODIFY_VALUE 4
extern  enum clnt_stat modify_value_1();
extern  bool_t modify_value_1_svc();
#define DELETE_KEY 5
extern  enum clnt_stat delete_key_1();
extern  bool_t delete_key_1_svc();
#define EXIST 6
extern  enum clnt_stat exist_1();
extern  bool_t exist_1_svc();
extern int claves_rpc_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_p_paquete (XDR *, p_paquete*);
extern  bool_t xdr_params (XDR *, params*);
extern  bool_t xdr_get_value_res (XDR *, get_value_res*);

#else /* K&R C */
extern bool_t xdr_p_paquete ();
extern bool_t xdr_params ();
extern bool_t xdr_get_value_res ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_CLAVESRPC_H_RPCGEN */
