/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "clavesRPC.h"

bool_t
xdr_p_paquete (XDR *xdrs, p_paquete *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->x))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->y))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->z))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_params (XDR *xdrs, params *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->key, 255))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->value1, 255))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->N_value2))
		 return FALSE;
	 if (!xdr_array (xdrs, (char **)&objp->V_value2.V_value2_val, (u_int *) &objp->V_value2.V_value2_len, 32,
		sizeof (float), (xdrproc_t) xdr_float))
		 return FALSE;
	 if (!xdr_p_paquete (xdrs, &objp->value3))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_get_value_res (XDR *xdrs, get_value_res *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->result))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->value1, 255))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->N_value2))
		 return FALSE;
	 if (!xdr_array (xdrs, (char **)&objp->V_value2.V_value2_val, (u_int *) &objp->V_value2.V_value2_len, 32,
		sizeof (float), (xdrproc_t) xdr_float))
		 return FALSE;
	 if (!xdr_p_paquete (xdrs, &objp->value3))
		 return FALSE;
	return TRUE;
}
